spring.application.name=lab9
spring.jpa.hibernate.ddl-auto=update
server.port=9090
spring.datasource.url=jdbc:mysql://localhost:3306/tdtu_java_tech_labs
spring.datasource.username=root
spring.datasource.password=Truong2209@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
lab9.upload-dir=src/main/resources/static
lab9.signer-key=0zyrZ7gaZCP/bIFTKMLLyuJXj8od3xeE4FDbsFGi1soFZNqvYCNQdb7lAUEVo=Ni41Qw8LEVLIHRHJIuvebQeUFjCx3SFNMtyXqLovUp1srRvDMC4NzAJuUHt4Uu=4hoCAEqg7IV=/pGEq=Sywo4!f5GG8XgQeZ4at330LC41E!6hlBTBJ!-hYI7SXjb!RQlCr88mfqR3wVw-0zwbYWGESIs7CU72y!w9kAKxTiVQQU5F9fujgoahnI3IkM-uG1n
